### ISSUE TITLE
... I think `drivers/kernelsu` is symlinked to the wrong place

### ISSUE THREAD

**Issue by th1nhhdk** [XperiaBrickers/kernel_sony_sm8250#2]
`drivers/kernelsu` should be symlinked to `../KernelSU/kernel/`, not `../../../KernelSU/kernel/`

after fixing that the kernel builds

**Comment by ghost** [comment]
Make a pull request and I'll accept

**Comment by th1nhhdk** [comment]
Fixed in #3
